CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_RING_BUFFER=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_OUTPUT=y
# CONFIG_LOG_MODE_IMMEDIATE=y # better for crash debugging
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_UART=n